export const cvData = {
  profile: {
    fullName: "Dr. Ajay Krishnath Gaikwad",
    title: "Professor & Head, Civil Engineering Department",
    institution: "Pimpri Chinchwad College of Engineering (PCCoE), Pune",
    degrees: ["Ph.D. (Civil)", "M.Tech. (CM)", "B.E. (Civil)"],
    memberships: ["LM QCFI-049903118057", "LM IEI AM094123-1", "LM ISTE"],
    email: "ajay.gaikwad@pccoepune.org",
    phones: ["+91 9822406840", "7420995740"],
    address: "Swaraaj Avenue, Flat 604, S.B. Patil School Road, Ravet, Pune 412102",
    dob: "10th June 1977",
    experience: {
      total: "27 Years",
      teaching: "24.5 Years",
      industrial: "2.5 Years",
      pccoe: "23+ Years",
    },
    socials: {
      youtube: "https://www.youtube.com/channel/UCzggPV5gezmNMKmenzi1nYA",
    },
    youtubeStats: {
      videos: 39,
      subscribers: "1600+",
      views: "1.9L+",
      topics: ["Engineering Mechanics", "Surveying"],
    },
  },
  phd: {
    completed: "15/09/2020",
    guide: "Dr. S.B. Thakare",
    title: "Dispatching Schedule Optimization for Ready Mix Concrete (PGSPhD319)",
    abstract: "Focuses on optimizing RMC truck dispatching using soft computing, GA, GPS for uninterrupted schedules, minimizing wait times.",
    keywords: ["RMC Optimization", "Genetic Algorithms (GA)", "GPS in Logistics"],
  },
  academicQualifications: [
    { degree: "PhD Civil", institution: "DY Patil COE Pimpri, SPPU", year: "2015-2020", detail: "RMC Optimization" },
    { degree: "M.Tech CM", institution: "COE Pune", year: "2014", detail: "8.10 CGPA, 2nd Rank" },
    { degree: "B.E. Civil", institution: "WIT Solapur", year: "1998", detail: "73.05%, 2nd Rank" },
  ],
  experienceTimeline: [
    { role: "Professor & HoD", duration: "May 2024 - Present", location: "PCCoE Pune" },
    { role: "Professor", duration: "Nov 2022 - May 2024", location: "PCCoE Pune" },
    { role: "Former Associate Dean (SDW)", duration: "2020 - 2024", location: "PCCoE Pune" },
    { role: "PhD Research Guide", duration: "2022 - Present", location: "SPPU" },
    { role: "PG Coordinator (Construction Mgmt)", duration: "2019 - 2024", location: "PCCoE Pune" },
    { role: "Associate Professor", duration: "2016 - 2022", location: "PCCoE Pune" },
    { role: "Assistant Professor", duration: "2014 - 2016", location: "PCCoE Pune" },
    { role: "Sr Lecturer / Lecturer", duration: "2002 - 2014", location: "PCCoE Pune" },
  ],
  achievements: [
    "2nd Rank in BE (WIT Solapur) and M.Tech (COE Pune)",
    "GATE 2002 (AIR 3842) & 2006 (AIR 2439) Qualified",
    "MPSC 2013 Mains & PGCET 2013-14 Qualified",
    "AVISHKAR University Winner & Guide to State Winners",
    "Best Paper Award at NCTR 2019",
    "3 Patents Published (RMC Optimizer, Survey Area Calc, PET Concrete)",
    "3 Copyrights Registered (RMC Dispatching System, etc.)",
    "Author of 'Engineering Mechanics' (Nirali Prakashan, 2019/2023)",
    "Funding Recipient: BCUD SPPU (Rs1L), ATAL (Rs2L), PCERF (Rs3.45L)",
    "Resource Person for 30+ NBA, BoS, Interviews, and FDPs",
  ],
  research: {
    publications: {
      total: "Scopus/SCI: 7; Journals: 12+; Conferences: 8+",
      highlights: [
        "Genetic Algo RMC Dispatch (IJRTE 2019, Scopus)",
        "App for RMC Trucks (IJITEE 2019, Scopus)",
        "Waste Water Management (YMER 2022)",
        "Defects in Concrete (IJRAR 2023)",
      ],
    },
    guiding: "Pravin Chate (PCB Slag in Concrete, since 2023)",
    vivaChair: "Multiple (e.g., Akshy Barkale 2023)",
  },
  projects: {
    ugCount: "12+",
    pgCount: "10+",
    themes: ["Prefabrication", "GPS Tracking", "Eco Concrete", "RMC Feasibility", "Lightweight Concrete"],
  },
  technicalSkills: ["C/C++", "MATLAB/GA", "Data Structures", "Soft Computing"],
};
